"""env_bootstrap 测试：配置解析、provider 收集、.env 引导生成。"""
import json
from unittest.mock import patch

import pytest

import env_bootstrap
from env_bootstrap import (
    _collect_providers,
    _normalize_base_url,
    _parse_env_file,
    _parse_model_yaml,
    _refinery_env_configured,
    ensure_refinery_env,
)

YAML_SAMPLE = """# Model connection configs
models:
  kimi:
    provider: kimi
    modelId: kimi-latest
    baseUrl: ${KIMI_BASE_URL}
    apiKey: ${KIMI_API_KEY}

  qwen3.7-max:
    provider: qwen
    modelId: qwen3.7-max
    baseUrl: ${QWEN_BASE_URL}
    apiKey: ${QWEN_API_KEY}

  qwen-vl-max:
    provider: qwen
    modelId: qwen-vl-max
    baseUrl: ${QWEN_BASE_URL}
    apiKey: ${QWEN_API_KEY}

  deepseek-v4-flash:
    provider: deepseek
    modelId: deepseek-v4-flash
    baseUrl: ${DEEPSEEK_BASE_URL}
    apiKey: ${DEEPSEEK_API_KEY}

routes:
  default: kimi
"""

SERVER_ENV_SAMPLE = """# Generated by tools/deploy.sh
KIMI_BASE_URL=https://api.moonshot.cn
KIMI_API_KEY=sk-kimi-xxx
QWEN_BASE_URL=https://dashscope.aliyuncs.com/compatible-mode
QWEN_API_KEY=sk-qwen-xxx
DEEPSEEK_BASE_URL=https://api.deepseek.com
DB_HOST=localhost
DB_PORT=3306
DB_USER=ai_k12
DB_PASS=secret-pass
DB_NAME=ai_k12
JWT_SECRET=abc
"""


class TestPathConstants:
    """回归：project_root 曾错算为 tools/（少了层级），导致 SERVER_ENV 等
    指向 tools/apps/server/.env（不存在），配置引导/模型菜单全部失效。"""

    def test_project_root_is_repo_root(self):
        import env_bootstrap
        assert env_bootstrap.project_root.name != "tools"
        assert (env_bootstrap.project_root / "apps" / "server").is_dir()
        assert (env_bootstrap.project_root / "tools" / "db").is_dir()

    def test_deploy_artifact_paths(self):
        import env_bootstrap
        # SERVER_ENV = <repo>/apps/server/.env；MODEL_YAML 在 apps/server/src/ai-core/ 下
        assert env_bootstrap.SERVER_ENV == env_bootstrap.project_root / "apps" / "server" / ".env"
        assert env_bootstrap.MODEL_YAML.parent.name == "ai-core"
        assert env_bootstrap.MODEL_YAML.name == "model-routes.yaml"
        assert env_bootstrap.DEPLOY_STATE.parent.name == "runtime"
        assert env_bootstrap.REFINERY_ENV.parent.name == "data-refinery"


class TestParseEnvFile:
    def test_basic(self, tmp_path):
        f = tmp_path / "server.env"
        f.write_text(SERVER_ENV_SAMPLE, encoding="utf-8")
        env = _parse_env_file(f)
        assert env["KIMI_API_KEY"] == "sk-kimi-xxx"
        assert env["DB_PASS"] == "secret-pass"

    def test_comments_quotes_and_blank(self, tmp_path):
        f = tmp_path / "env"
        f.write_text("# comment\n\nKEY='quoted'\nBARE=no-quote\nBAD LINE\n", encoding="utf-8")
        env = _parse_env_file(f)
        assert env == {"KEY": "quoted", "BARE": "no-quote"}


class TestParseModelYaml:
    def test_main_key_preferred_over_first_block(self, tmp_path):
        f = tmp_path / "model-routes.yaml"
        f.write_text(YAML_SAMPLE, encoding="utf-8")
        models = _parse_model_yaml(f)
        # qwen 有两个块（qwen3.7-max 主模型 + qwen-vl-max），必须选主 key
        assert models["qwen"] == "qwen3.7-max"
        assert models["kimi"] == "kimi-latest"
        assert models["deepseek"] == "deepseek-v4-flash"

    def test_fallback_to_first_block_when_main_key_missing(self, tmp_path):
        yaml_text = """models:
  custom-qwen:
    provider: qwen
    modelId: qwen-custom
routes:
  default: custom-qwen
"""
        f = tmp_path / "model-routes.yaml"
        f.write_text(yaml_text, encoding="utf-8")
        assert _parse_model_yaml(f) == {"qwen": "qwen-custom"}


class TestNormalizeBaseUrl:
    def test_deploy_defaults_become_empty(self):
        assert _normalize_base_url("kimi", "https://api.moonshot.cn") == ""
        assert _normalize_base_url("qwen", "https://dashscope.aliyuncs.com/compatible-mode") == ""
        assert _normalize_base_url("gemini", "https://generativelanguage.googleapis.com/") == ""
        assert _normalize_base_url("deepseek", "https://api.deepseek.com") == ""

    def test_custom_proxy_kept(self):
        assert _normalize_base_url("kimi", "https://my-proxy.local/v1") == "https://my-proxy.local/v1"

    def test_empty(self):
        assert _normalize_base_url("kimi", "") == ""


class TestCollectProviders:
    def test_server_env_priority_and_state_fallback(self):
        server_env = {"KIMI_BASE_URL": "https://api.moonshot.cn", "KIMI_API_KEY": "sk-a"}
        yaml_models = {"kimi": "kimi-latest"}
        state = {
            "LLM_KIMI_API_KEY": "sk-state",           # 应被 server_env 覆盖
            "LLM_DEEPSEEK_MODEL": "deepseek-v4-flash",  # state 兜底
            "LLM_DEEPSEEK_BASE_URL": "https://api.deepseek.com",
            "LLM_DEEPSEEK_API_KEY": "sk-ds",
        }
        providers = _collect_providers(server_env, yaml_models, state)
        assert providers["kimi"] == {
            "model": "kimi-latest", "base_url": "https://api.moonshot.cn", "api_key": "sk-a",
        }
        assert providers["deepseek"]["api_key"] == "sk-ds"
        assert providers["deepseek"]["model"] == "deepseek-v4-flash"
        # qwen/gemini 完全未配置
        assert providers["qwen"]["api_key"] == ""


def _setup_sources(tmp_path, server_env_text=SERVER_ENV_SAMPLE, yaml_text=YAML_SAMPLE,
                   state=None):
    server_env = tmp_path / "server.env"
    server_env.write_text(server_env_text, encoding="utf-8")
    yaml_file = tmp_path / "model-routes.yaml"
    yaml_file.write_text(yaml_text, encoding="utf-8")
    state_file = tmp_path / "deploy.state.json"
    if state is not None:
        state_file.write_text(json.dumps(state), encoding="utf-8")
    return server_env, yaml_file, state_file


class TestEnsureRefineryEnv:
    def test_already_configured_skips(self, tmp_path):
        refinery_env = tmp_path / ".env"
        refinery_env.write_text("LLM_PROVIDER=kimi\nLLM_MODEL=kimi-latest\nLLM_AUTH_TOKEN=sk\n",
                                encoding="utf-8")
        with patch.object(env_bootstrap, "_write_refinery_env") as wr:
            assert ensure_refinery_env(refinery_env=refinery_env,
                                       server_env_path=tmp_path / "nope") is True
        wr.assert_not_called()

    def test_missing_server_env_exits(self, tmp_path):
        with pytest.raises(SystemExit):
            ensure_refinery_env(refinery_env=tmp_path / ".env",
                               server_env_path=tmp_path / "nope")

    def test_single_provider_auto_selected(self, tmp_path, capsys):
        # 只有 kimi 配置了 key → 自动选择，不交互
        server_env, yaml_file, state_file = _setup_sources(
            tmp_path, server_env_text="KIMI_BASE_URL=https://api.moonshot.cn\nKIMI_API_KEY=sk-kimi-xxx\n")
        refinery_env = tmp_path / "refinery.env"
        with patch.object(env_bootstrap, "_apply_env") as ap:
            assert ensure_refinery_env(refinery_env=refinery_env, server_env_path=server_env,
                                       yaml_path=yaml_file, state_path=state_file) is True
        ap.assert_called_once_with(refinery_env)
        content = refinery_env.read_text(encoding="utf-8")
        assert "LLM_PROVIDER=kimi" in content
        assert "LLM_MODEL=kimi-latest" in content
        assert "LLM_AUTH_TOKEN=sk-kimi-xxx" in content
        # deploy 默认 URL 规范化为空（用 per-provider 默认端点）
        assert "LLM_BASE_URL=" in content
        assert "DB_HOST=localhost" in content
        assert "DB_PASS=secret-pass" not in content  # server env 无 DB 时用默认值

    def test_interactive_choice(self, tmp_path, monkeypatch):
        server_env, yaml_file, state_file = _setup_sources(tmp_path)
        refinery_env = tmp_path / "refinery.env"
        monkeypatch.delenv("REFINERY_PROVIDER", raising=False)
        calls = []
        with patch.object(env_bootstrap, "_apply_env"), \
                patch.object(env_bootstrap, "_choose_provider", return_value="qwen") as choose:
            assert ensure_refinery_env(refinery_env=refinery_env, server_env_path=server_env,
                                       yaml_path=yaml_file, state_path=state_file) is True
        choose.assert_called_once()
        content = refinery_env.read_text(encoding="utf-8")
        assert "LLM_PROVIDER=qwen" in content
        assert "LLM_MODEL=qwen3.7-max" in content

    def test_refinery_provider_env_var(self, tmp_path, monkeypatch):
        server_env, yaml_file, state_file = _setup_sources(tmp_path)
        refinery_env = tmp_path / "refinery.env"
        monkeypatch.setenv("REFINERY_PROVIDER", "QWEN")
        with patch.object(env_bootstrap, "_apply_env"):
            assert ensure_refinery_env(refinery_env=refinery_env, server_env_path=server_env,
                                       yaml_path=yaml_file, state_path=state_file) is True
        content = refinery_env.read_text(encoding="utf-8")
        assert "LLM_PROVIDER=qwen" in content

    def test_refinery_provider_invalid_exits(self, tmp_path, monkeypatch):
        server_env, yaml_file, state_file = _setup_sources(tmp_path)
        monkeypatch.setenv("REFINERY_PROVIDER", "openai")  # deploy 未配置
        with pytest.raises(SystemExit):
            ensure_refinery_env(refinery_env=tmp_path / "refinery.env",
                                server_env_path=server_env, yaml_path=yaml_file,
                                state_path=state_file)

    def test_state_file_rescues_missing_server_key(self, tmp_path):
        # server .env 只有 kimi key；deepseek 三元组全在 state 里
        server_env, yaml_file, state_file = _setup_sources(
            tmp_path,
            server_env_text="KIMI_BASE_URL=https://api.moonshot.cn\nKIMI_API_KEY=sk-kimi-xxx\n",
            state={"LLM_DEEPSEEK_MODEL": "deepseek-v4-flash",
                   "LLM_DEEPSEEK_BASE_URL": "https://api.deepseek.com",
                   "LLM_DEEPSEEK_API_KEY": "sk-ds"})
        refinery_env = tmp_path / "refinery.env"
        with patch.object(env_bootstrap, "_apply_env"):
            assert ensure_refinery_env(refinery_env=refinery_env, server_env_path=server_env,
                                       yaml_path=yaml_file, state_path=state_file,
                                       input_fn=lambda _: "2") is True
        content = refinery_env.read_text(encoding="utf-8")
        # kimi(server env) + deepseek(state) 都可用，选 2 → deepseek
        assert "LLM_PROVIDER=deepseek" in content
        assert "LLM_AUTH_TOKEN=sk-ds" in content

    def test_no_complete_provider_exits(self, tmp_path):
        server_env, yaml_file, state_file = _setup_sources(
            tmp_path,
            server_env_text="KIMI_BASE_URL=https://api.moonshot.cn\n",  # 只有 URL 没有 key
            yaml_text="")
        with pytest.raises(SystemExit):
            ensure_refinery_env(refinery_env=tmp_path / "refinery.env",
                                server_env_path=server_env, yaml_path=yaml_file,
                                state_path=state_file)

    def test_db_values_copied_from_server_env(self, tmp_path):
        server_env, yaml_file, state_file = _setup_sources(tmp_path)
        refinery_env = tmp_path / "refinery.env"
        with patch.object(env_bootstrap, "_apply_env"):
            ensure_refinery_env(refinery_env=refinery_env, server_env_path=server_env,
                                yaml_path=yaml_file, state_path=state_file,
                                input_fn=lambda _: "1")
        content = refinery_env.read_text(encoding="utf-8")
        assert "DB_HOST=localhost" in content
        assert "DB_USER=ai_k12" in content
        assert "DB_PASS=secret-pass" in content
        assert "DB_NAME=ai_k12" in content


class TestRefineryEnvConfigured:
    def test_missing_file(self, tmp_path):
        assert _refinery_env_configured(tmp_path / "nope") is False

    def test_incomplete(self, tmp_path):
        f = tmp_path / ".env"
        f.write_text("LLM_PROVIDER=kimi\nLLM_MODEL=kimi-latest\n", encoding="utf-8")  # 缺 token
        assert _refinery_env_configured(f) is False

    def test_complete(self, tmp_path):
        f = tmp_path / ".env"
        f.write_text("LLM_PROVIDER=kimi\nLLM_MODEL=kimi-latest\nLLM_AUTH_TOKEN=sk\n", encoding="utf-8")
        assert _refinery_env_configured(f) is True
